# Generated by Django 4.2.16 on 2024-11-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emigrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('academic_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Холост/Не замужем'), ('married', 'Женат/Замужем'), ('divorced', 'Разведен/Разведена'), ('widowed', 'Вдовец/Вдова')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('profession', models.CharField(max_length=100)),
                ('country_of_emigration', models.CharField(max_length=100)),
                ('reason_for_emigration', models.TextField()),
            ],
        ),
    ]
